export const testOrders = [
  {
    number: '034534',
    name: 'Death Star Starship Main бургер',
    date: 'Вчера, 13:20 i-GMT+3',
    price: 480,
    status: 'done',
    ingredients: [
      "https://code.s3.yandex.net/react/code/bun-02-mobile.png",
      "https://code.s3.yandex.net/react/code/meat-03-mobile.png",
      "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
    ]
  },
  {
    number: '025534',
    name: 'Death Star Starship Main бургер',
    date: 'Вчера, 13:20 i-GMT+3',
    price: 480,
    status: 'done',
    ingredients: [
      "https://code.s3.yandex.net/react/code/bun-02-mobile.png",
      "https://code.s3.yandex.net/react/code/meat-03-mobile.png",
      "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
      "https://code.s3.yandex.net/react/code/bun-02-mobile.png",
      "https://code.s3.yandex.net/react/code/meat-03-mobile.png",
      "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
    ]
  },
  {
    number: '022222',
    name: 'Death Star Starship Main бургер',
    date: 'Вчера, 13:20 i-GMT+3',
    price: 480,
    status: 'done',
    ingredients: [
      "https://code.s3.yandex.net/react/code/bun-02-mobile.png",
      "https://code.s3.yandex.net/react/code/meat-03-mobile.png",
      "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
      "https://code.s3.yandex.net/react/code/bun-02-mobile.png",
      "https://code.s3.yandex.net/react/code/meat-03-mobile.png",
      "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
      "https://code.s3.yandex.net/react/code/bun-02-mobile.png",
      "https://code.s3.yandex.net/react/code/meat-03-mobile.png",
      "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
    ]
  },
  {
    number: '022222',
    name: 'Death Star Starship Main бургер',
    date: 'Вчера, 13:20 i-GMT+3',
    price: 480,
    status: 'done',
    ingredients: [
      "https://code.s3.yandex.net/react/code/bun-02-mobile.png",
      "https://code.s3.yandex.net/react/code/meat-03-mobile.png",
      "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
      "https://code.s3.yandex.net/react/code/bun-02-mobile.png",
      "https://code.s3.yandex.net/react/code/meat-03-mobile.png",
      "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
      "https://code.s3.yandex.net/react/code/bun-02-mobile.png",
      "https://code.s3.yandex.net/react/code/meat-03-mobile.png",
      "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
    ]
  },
  {
    number: '022222',
    name: 'Death Star Starship Main бургер',
    date: 'Вчера, 13:20 i-GMT+3',
    price: 480,
    status: 'done',
    ingredients: [
      "https://code.s3.yandex.net/react/code/bun-02-mobile.png",
      "https://code.s3.yandex.net/react/code/meat-03-mobile.png",
      "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
      "https://code.s3.yandex.net/react/code/bun-02-mobile.png",
      "https://code.s3.yandex.net/react/code/meat-03-mobile.png",
      "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
      "https://code.s3.yandex.net/react/code/bun-02-mobile.png",
      "https://code.s3.yandex.net/react/code/meat-03-mobile.png",
      "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
    ]
  },
  {
    number: '022222',
    name: 'Death Star Starship Main бургер',
    date: 'Вчера, 13:20 i-GMT+3',
    price: 480,
    status: 'done',
    ingredients: [
      "https://code.s3.yandex.net/react/code/bun-02-mobile.png",
      "https://code.s3.yandex.net/react/code/meat-03-mobile.png",
      "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
      "https://code.s3.yandex.net/react/code/bun-02-mobile.png",
      "https://code.s3.yandex.net/react/code/meat-03-mobile.png",
      "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
      "https://code.s3.yandex.net/react/code/bun-02-mobile.png",
      "https://code.s3.yandex.net/react/code/meat-03-mobile.png",
      "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
    ]
  },
  {
    number: '022222',
    name: 'Death Star Starship Main бургер',
    date: 'Вчера, 13:20 i-GMT+3',
    price: 480,
    status: 'done',
    ingredients: [
      "https://code.s3.yandex.net/react/code/bun-02-mobile.png",
      "https://code.s3.yandex.net/react/code/meat-03-mobile.png",
      "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
      "https://code.s3.yandex.net/react/code/bun-02-mobile.png",
      "https://code.s3.yandex.net/react/code/meat-03-mobile.png",
      "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
      "https://code.s3.yandex.net/react/code/bun-02-mobile.png",
      "https://code.s3.yandex.net/react/code/meat-03-mobile.png",
      "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
    ]
  },
  {
    number: '022222',
    name: 'Death Star Starship Main бургер',
    date: 'Вчера, 13:20 i-GMT+3',
    price: 480,
    status: 'done',
    ingredients: [
      "https://code.s3.yandex.net/react/code/bun-02-mobile.png",
      "https://code.s3.yandex.net/react/code/meat-03-mobile.png",
      "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
      "https://code.s3.yandex.net/react/code/bun-02-mobile.png",
      "https://code.s3.yandex.net/react/code/meat-03-mobile.png",
      "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
      "https://code.s3.yandex.net/react/code/bun-02-mobile.png",
      "https://code.s3.yandex.net/react/code/meat-03-mobile.png",
      "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
    ]
  },
  {
    number: '075633',
    name: 'Death Star Starship Main бургер',
    date: 'Вчера, 13:20 i-GMT+3',
    price: 480,
    status: 'active',
    ingredients: [
      "https://code.s3.yandex.net/react/code/bun-02-mobile.png",
      "https://code.s3.yandex.net/react/code/meat-03-mobile.png",
      "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
      "https://code.s3.yandex.net/react/code/meat-03-mobile.png",
      "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
    ]
  },
]
